tdewolff:
  html:
    keepComments: false
    keepConditionalComments: false
    keepDefaultAttrVals: true
    keepDocumentTags: true
    keepEndTags: true
    keepQuotes: true
    keepWhitespace: false
